project_id = "lfsmtsnakdaukxgrqynk"

[functions.me]
verify_jwt = false

[functions.students]
verify_jwt = false

[functions.rooms]
verify_jwt = false

[functions.assignments]
verify_jwt = false

[functions.help-requests]
verify_jwt = false

[functions.student-portal]
verify_jwt = false
